/*-
 * ---license-start
 * European Digital COVID Certificate Validation Decorator Service / dgca-validation-decorator
 * ---
 * Copyright (C) 2021 T-Systems International GmbH and all other contributors
 * ---
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ---license-end
 */

package eu.europa.ec.dgc.validation.decorator.entity;

import lombok.Data;

@Data
public class ValidationServiceInitializeRequest {

    // @NotNull / ECDSA key generated by the user/wallet.
    private String pubKey;

    // @NotNull / Use Crypto Metod accoding to JWT definitions in RFC7518, e.g. ES256/PS256.
    private String keyType;

    // Optional callback URL.
    private String callback;
    
    // @NotNull / Base64 encoded, random 16 bytes long array
    private String nonce;
}
