package eu.europa.ec.dgc.validation.decorator.dto;

import lombok.Builder;
import lombok.Value;

@Value
@Builder
public class QRCodeDto {

	// Type of the requested protocol
	// used from application.yml
	private String protocol;
	
	// SemVer version number
	// used from application.yml
	private String protocolVersion;
	
	// URL to the service provider identity document
	private String serviceidentity;
	
	// Service Validation Document
	private String validationidentity;
	
	// JWT for Validation Decorator endpoints and contains the information about the booking.
	private String token;
	
	// Consent text which is shown to the user by the wallet app
	private String consent;
	
	// Subject of the Request
	// generated by SubjectService
	private String subject;
	
	// Company Name
	private String serviceprovider;
}
